#!/usr/bin/with-contenv bash

while [ ! -f "/etc/plexdrv/config.json" ] || [ ! -f "/etc/plexdrv/token.json" ]
do
	echo "Waiting for plexdrive configuration files ..."
	sleep 30
done

umask 022

IFS=" " read -r -a RUN_ARRAY <<< "$RUN_OPTS"

touch /cache/cache.bolt && chmod 666 /cache/cache.bolt
mount_command="plexdrive mount -c /etc/plexdrv/ --cache-file=/cache/cache.bolt -v 3 --umask=0777 --chunk-size=100M --uid=$PLEX_UID --gid=$PLEX_GID -o allow_other /encrypted ${RUN_ARRAY[@]}"

echo "Executing => $mount_command"
mkdir /encrypted /decrypted
chmod 777 /encrypted /decrypted
exec \
	s6-setuidgid plex $mount_command
