version: '2'
services:
  plex:
   build: ./
   image: kilhaasi/pms
   container_name: pms
   volumes:
    - ~/Docker/Plex-Video/plex_cfg:/config
    - ~/Docker/Plex-Video/plexdrv:/etc/plexdrv
    - ~/Docker/Plex-Video/video:/mnt/video
    - ~/lala:/mnt/lala
   environment:
   - TZ=DE
   - BACKUP=gdrive:/Backup/Plex-Dev
   - CRON=4
#  - PLEX_CLAIM=claim-YHkzWzT_MNnRrX1eLKAk
   - S6_KILL_FINISH_MAXTIME=20000
   ports:
   - 32400:32400
   devices:
   - /dev/fuse
   privileged: true
   cap_add:
   - MKNOD
   - SYS_ADMIN
