version: '2'
services:
  plex:
#  build: ./
   image: kilhaasi/pms
   container_name: pms
   volumes:
   - /Video:/Video:shared
   - /Transcode:/Transcode
   - /Docker/Plex-Video/plex_cfg:/config
   - /Docker/Plex-Video/.rclone.conf:/root/.rclone.conf
   - /Docker/Plex-Video/plexdrv-cfg:/root/.plexdrive
   - /Docker/Plex-Video/enc-pwd:/root/enc-pwd
   - /Docker/Plex-Video/cache:/cache
   environment:
   - TZ=DE
   - BACKUP=gdrive:/Backup/Plex-Dev
   - CRON=4
   - PLEX_CLAIM=claim-z3PqezuUozjYLvv7LakC
   ports:
   - 32400:32400
   devices:
   - /dev/fuse
   privileged: true
   cap_add:
   - MKNOD
   - SYS_ADMIN

