version: '2'
services:
  plex:
   build: ./
   image: kilhaasi/pms-dev
   container_name: pms-dev
   volumes:
    - /Photo:/Photo
    - /Transcode:/Transcode
    - /Docker/Plex-Video/plex_cfg:/config
    - /Docker/Plex-Video/cache:/cache
    - /Docker/Plex-Video/plexdrv:/etc/plexdrv
   environment:
   - TZ=DE
   - BACKUP=gdrive:/Backup/Plex-Dev
   - CRON=4
   - PLEX_CLAIM=claim-z3PqezuUozjYLvv7LakC
   ports:
   - 32400:32400
   devices:
   - /dev/fuse
   privileged: true
   cap_add:
   - MKNOD
   - SYS_ADMIN

