version: '2'
services:
  plex:
   build: ./
   image: kilhaasi/pms
   container_name: pms
#   depends_on:
#   - plexdrv
   volumes:
   - /Video:/Video:shared
   - /Transcode:/Transcode
   - /Docker/Plex-Video/plex_cfg:/config
   - ./.rclone.conf:/root/.rclone.conf
   environment:
   - TZ=DE
   - BACKUP=gdrive:/Backup/Plex-Dev
   - CRON=4
   - PLEX_CLAIM=claim-z3PqezuUozjYLvv7LakC
   ports:
   - 32400:32400
