#!/usr/bin/with-contenv bash
mkdir /encrypted
rclone mount --daemon --allow-other gcache:/ /encrypted
while [ ! -f "/encrypted/gocryptfs.conf" ]
do
 echo "Waiting for gocryptfs.conf to appear..."
 sleep 1
done

mkdir -pv /Video
chmod 777 /Video

s6-setuidgid plex gocryptfs -passfile /etc/plexdrv/enc-pwd /encrypted/ /Video


until false
do
 true
 sleep 1
done
